# area for all of the feature enabling/disabling
PhantomToggle: true
EntityCrammingDisable: true

# all of the below are config used by the plugins
# whether to disable entity cramming or not
doEntityCramming: true
