name: Utilities-OG
version: '1.1'
main: me.barny1094875.utilitiesog.Utilities_OG
api-version: 1.18
commands:
  togglephantoms:
    usage: /togglephantoms
  togglecramming:
    usage: /togglecramming
permissions:
  util.candisablephantoms:
    default: op
  util.candisablecramming:
    default: op
