name: Utilities-OG
authors: [ christianniehaus, NotAlexNoyle ]
version: '1.2'
main: me.barny1094875.utilitiesog.Utilities_OG
api-version: 1.18
depend: [ NBTAPI ]
commands:
  utilities:
    usage: /utilites
  buy:
    usage: /buy

permissions:
  util.candisablecramming:
    default: op