name: Utilities-OG
version: '1.0'
main: me.barny1094875.utilitiesog.Utilities_OG
api-version: 1.18
depend: [ NBTAPI ]
commands:
  utilities:
    usage: /utilites
permissions:
  util.candisablecramming:
    default: op
